@extends('layouts.admin.template')

@section('content')

<div class="card custom-card">
    <div class="card-header">
        <div class="card-title">Generate Pumping Bill</div>
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route('pumping-bills.store') }}">
            @csrf

            <!-- ====== Report Selection ====== -->
            <div class="row mb-4">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="reportSelect">Link to Existing Report (Optional)</label>
                        <select id="reportSelect" class="form-control select2" style="width: 100%;">
                            <option value="">-- Select a report --</option>
                            @foreach($reports as $report)
                                <option value="{{ $report->id }}" data-type="fire" data-id="{{ $report->id }}">
                                    {{ $report->fire_report_no }}
                                </option>
                            @endforeach
                        </select>
                    </div>
                </div>
            </div>

            <!-- Hidden fields -->
            <input type="hidden" name="report_type" id="reportType" value="">
            <input type="hidden" name="report_id" id="reportId" value="">

            <!-- ====== Organisation Details ====== -->
            <div class="row mb-4">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Organisation Name <span class="text-danger">*</span></label>
                        <input type="text" name="organisation_name" id="organisationName" class="form-control" required>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Address</label>
                        <input type="text" name="address" id="address" class="form-control">
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label>Mobile</label>
                        <input type="text" name="mobile" id="mobile" class="form-control">
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label>Email</label>
                        <input type="email" name="email" id="email" class="form-control">
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label>Service Description</label>
                        <input type="text" name="service_description" id="serviceDescription" class="form-control">
                    </div>
                </div>
            </div>

            <hr>

            <!-- ====== Fuel Rate ====== -->
            <div class="row mb-4">
                <div class="col-md-3">
                    <div class="card border shadow-sm">
                        <div class="card-body">
                            <label class="fw-bold">Fuel Rate (₹/litre)</label>
                            <input type="number" step="0.01" name="diesel_rate" id="fuelRate" class="form-control" value="95">
                        </div>
                    </div>
                </div>
            </div>

            <hr>

            <!-- ====== PERSONNEL EXPENSE (with Days) ====== -->
            <div class="d-flex justify-content-between align-items-center mb-3">
                <h5 class="mb-0">Personnel Expense</h5>
                <button type="button" class="btn btn-primary btn-sm" id="addPersonnelRow">+</button>
            </div>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th width="20%">Designation</th>
                            <th width="12%">No of Persons</th>
                            <th width="12%">No of Days</th>
                            <th width="16%">Monthly Expense</th>
                            <th width="12%">DA %</th>
                            <th width="18%">Total</th>
                            <th width="5%">Action</th>
                        </tr>
                    </thead>
                    <tbody id="personnelTable">
                        <!-- Generated by JavaScript -->
                    </tbody>
                </table>
            </div>
            <hr>

            <!-- ====== VEHICLE EXPENSE ====== -->
            <div class="d-flex justify-content-between align-items-center mb-3">
                <h5 class="mb-0">Vehicle Expense</h5>
                <button type="button" class="btn btn-primary btn-sm" id="addVehicleRow">+</button>
            </div>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Vehicle Category</th>
                            <th>Mileage Type</th>
                            <th>Mileage</th>
                            <th>KM</th>
                            <th>Fuel Used</th>
                            <th>Total</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody id="vehicleTable">
                        <!-- Generated by JavaScript -->
                    </tbody>
                </table>
            </div>
            <hr>

            <!-- ====== EQUIPMENT EXPENSE ====== -->
            <div class="d-flex justify-content-between align-items-center mb-3">
                <h5 class="mb-0">Equipment Expense</h5>
                <button type="button" class="btn btn-primary btn-sm" id="addEquipmentRow">+</button>
            </div>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Equipment Category</th>
                            <th>Mileage Type</th>
                            <th>Mileage</th>
                            <th>Hours</th>
                            <th>Fuel Used</th>
                            <th>Total</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody id="equipmentTable">
                        <!-- Generated by JavaScript -->
                    </tbody>
                </table>
            </div>
            <hr>

            <!-- ====== BILLING SUMMARY ====== -->
            <div class="card mt-4">
                <div class="card-header bg-primary text-white">Billing Summary</div>
                <div class="card-body p-0">
                    <div class="table-responsive">
                        <table class="table table-bordered mb-0">
                            <thead>
                                <tr>
                                    <th width="10%">#</th>
                                    <th>Billing</th>
                                    <th width="25%">Amount</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>1</td>
                                    <td>Fuel expense for pumping operation of Fire Vehicles & Equipments</td>
                                    <td><input type="text" name="fuel_expense" id="fuelExpense" class="form-control" readonly></td>
                                </tr>
                                <tr>
                                    <td>2</td>
                                    <td>Depreciation expenses of vehicle 25% of fuel expenses</td>
                                    <td><input type="text" name="depreciation_expense" id="depreciationExpense" class="form-control" readonly></td>
                                </tr>
                                <tr>
                                    <td>3</td>
                                    <td>Salary / Allowances for Personnel etc.</td>
                                    <td><input type="text" name="personnel_expense" id="personnelExpense" class="form-control" readonly></td>
                                </tr>
                                <tr>
                                    <td>4</td>
                                    <td>CGST @9%</td>
                                    <td><input type="text" name="cgst_amount" id="cgstAmount" class="form-control" readonly></td>
                                </tr>
                                <tr>
                                    <td>5</td>
                                    <td>SGST @9%</td>
                                    <td><input type="text" name="sgst_amount" id="sgstAmount" class="form-control" readonly></td>
                                </tr>
                                <tr class="table-primary">
                                    <th colspan="2">Total Amount</th>
                                    <th><input type="text" name="total_amount" id="grandTotal" class="form-control fw-bold" readonly></th>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <div class="mt-4">
                <button type="submit" class="btn btn-success">Generate Bill</button>
            </div>
        </form>
    </div>
</div>

<!-- ====== Templates ====== -->
<!-- Personnel Row -->
<template id="personnelRowTemplate">
    <tr>
        <td>
            <select name="designation_id[]" class="form-control designation_select select2">
                <option value="">Select Designation</option>
                @foreach($designations as $designation)
                    <option value="{{ $designation->designation_id }}" data-expense="{{ $designation->monthly_basic_expense }}" data-da="{{ $designation->da_percent }}">
                        {{ $designation->designation->designation_name ?? '' }}
                    </option>
                @endforeach
            </select>
        </td>
        <td><input type="number" name="no_of_person[]" class="form-control no_of_person" value="1" min="1"></td>
        <td><input type="number" step="0.01" name="no_of_days[]" class="form-control no_of_days" value="1" min="0.5"></td>
        <td><input type="text" name="expense[]" class="form-control expense" readonly></td>
        <td><input type="text" name="da[]" class="form-control da" readonly></td>
        <td><input type="text" name="person_total[]" class="form-control person_total" readonly></td>
        <td><button type="button" class="btn btn-danger btn-sm removePersonnelRow">X</button></td>
    </tr>
</template>

<!-- Vehicle Row -->
<template id="vehicleRowTemplate">
    <tr>
        <td>
            <select name="vehicle_type_id[]" class="form-control vehicle_select select2">
                <option value="">Select Vehicle Category</option>
                @foreach($vehicles as $vehicle)
                    <option value="{{ $vehicle->id }}" data-mileage="{{ $vehicle->mileage_value ?? 0 }}" data-type="{{ $vehicle->mileage_type ?? '' }}">
                        {{ $vehicle->type }}
                    </option>
                @endforeach
            </select>
        </td>
        <td><input type="text" name="vehicle_mileage_type[]" class="form-control mileage_type" readonly></td>
        <td><input type="text" name="vehicle_mileage[]" class="form-control mileage_value" readonly></td>
        <td><input type="number" step="0.01" name="vehicle_running[]" class="form-control running_value" value="0"></td>
        <td><input type="text" name="vehicle_fuel_used[]" class="form-control vehicle_fuel_used" readonly></td>
        <td><input type="text" name="vehicle_total[]" class="form-control vehicle_total" readonly></td>
        <td><button type="button" class="btn btn-danger btn-sm removeVehicleRow">X</button></td>
    </tr>
</template>

<!-- Equipment Row -->
<template id="equipmentRowTemplate">
    <tr>
        <td>
            <select name="equipment_type_id[]" class="form-control equipment_select select2">
                <option value="">Select Equipment Category</option>
                @foreach($equipments as $equipment)
                    <option value="{{ $equipment->id }}" data-mileage="{{ $equipment->mileage_value ?? 0 }}" data-type="{{ $equipment->mileage_type ?? '' }}">
                        {{ $equipment->name }}
                    </option>
                @endforeach
            </select>
        </td>
        <td><input type="text" name="equipment_mileage_type[]" class="form-control equipment_mileage_type" readonly></td>
        <td><input type="text" name="equipment_mileage[]" class="form-control equipment_mileage_value" readonly></td>
        <td><input type="number" step="0.01" name="equipment_running[]" class="form-control equipment_running_value" value="0"></td>
        <td><input type="text" name="equipment_fuel_used[]" class="form-control equipment_fuel_used" readonly></td>
        <td><input type="text" name="equipment_total[]" class="form-control equipment_total" readonly></td>
        <td><button type="button" class="btn btn-danger btn-sm removeEquipmentRow">X</button></td>
    </tr>
</template>

@endsection

@section('scripts')
<!-- Select2 CSS/JS -->
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

<script>
$(document).ready(function() {

    // ============================================================
    // 1. HELPER FUNCTIONS TO CREATE ROWS
    // ============================================================

    function getPersonnelRow(designationId, persons, days, expense, da, total) {
        var template = document.getElementById('personnelRowTemplate');
        var clone = document.importNode(template.content, true);
        var row = clone.querySelector('tr');
        var select = row.querySelector('select.designation_select');
        if (designationId) select.value = designationId;
        row.querySelector('.no_of_person').value = persons || 1;
        row.querySelector('.no_of_days').value = days || 1;
        row.querySelector('.expense').value = expense || 0;
        row.querySelector('.da').value = da || 0;
        row.querySelector('.person_total').value = (total || 0).toFixed(2);
        return row;
    }

    function getVehicleRow(vehicleTypeId, running) {
        var template = document.getElementById('vehicleRowTemplate');
        var clone = document.importNode(template.content, true);
        var row = clone.querySelector('tr');
        var select = row.querySelector('select.vehicle_select');
        if (vehicleTypeId) select.value = vehicleTypeId;
        row.querySelector('.running_value').value = running || 0;
        return row;
    }

    function getEquipmentRow(equipmentTypeId, running) {
        var template = document.getElementById('equipmentRowTemplate');
        var clone = document.importNode(template.content, true);
        var row = clone.querySelector('tr');
        var select = row.querySelector('select.equipment_select');
        if (equipmentTypeId) select.value = equipmentTypeId;
        row.querySelector('.equipment_running_value').value = running || 0;
        return row;
    }

    // ============================================================
    // 2. SELECT2 INITIALIZERS (for all dropdowns)
    // ============================================================

    function initDesignationSelect(row) {
        $(row).find('.designation_select').select2({
            placeholder: 'Search designation...',
            allowClear: true,
            width: '100%'
        });
    }

    function initVehicleSelect(row) {
        $(row).find('.vehicle_select').select2({
            placeholder: 'Search vehicle category...',
            allowClear: true,
            width: '100%'
        });
    }

    function initEquipmentSelect(row) {
        $(row).find('.equipment_select').select2({
            placeholder: 'Search equipment category...',
            allowClear: true,
            width: '100%'
        });
    }

    // ============================================================
    // 3. TRIGGER FUNCTIONS (include init)
    // ============================================================

    function triggerVehicleRow(row) {
        $(row).find('.vehicle_select').trigger('change');
        $(row).find('.running_value').trigger('keyup');
        initVehicleSelect(row);
    }

    function triggerEquipmentRow(row) {
        $(row).find('.equipment_select').trigger('change');
        $(row).find('.equipment_running_value').trigger('keyup');
        initEquipmentSelect(row);
    }

    // ============================================================
    // 4. POPULATE TABLES
    // ============================================================

    function populatePersonnel(personnelArray) {
        var tbody = $('#personnelTable');
        tbody.empty();
        if (!personnelArray || personnelArray.length === 0) {
            var row = getPersonnelRow(null, 1, 1, 0, 0, 0);
            tbody.append(row);
            initDesignationSelect(row);
        } else {
            personnelArray.forEach(function(item) {
                var row = getPersonnelRow(item.designation_id, item.count, item.days || 1, item.expense, item.da, item.total);
                tbody.append(row);
                initDesignationSelect(row);
            });
        }
        calculateTotals();
    }

    function populateVehicles(vehicleArray) {
        var tbody = $('#vehicleTable');
        tbody.empty();
        if (!vehicleArray || vehicleArray.length === 0) {
            var row = getVehicleRow(null, 0);
            tbody.append(row);
            triggerVehicleRow(row);
        } else {
            vehicleArray.forEach(function(item) {
                var row = getVehicleRow(item.vehicle_type_id, item.running || 0);
                tbody.append(row);
                triggerVehicleRow(row);
            });
        }
        calculateTotals();
    }

    function populateEquipment(equipmentArray) {
        var tbody = $('#equipmentTable');
        tbody.empty();
        if (!equipmentArray || equipmentArray.length === 0) {
            var row = getEquipmentRow(null, 0);
            tbody.append(row);
            triggerEquipmentRow(row);
        } else {
            equipmentArray.forEach(function(item) {
                var row = getEquipmentRow(item.equipment_id, item.running || 0);
                tbody.append(row);
                triggerEquipmentRow(row);
            });
        }
        calculateTotals();
    }

    // ============================================================
    // 5. INITIALISE SELECT2 ON EXISTING ROWS (on page load)
    // ============================================================

    // In case there are any selects rendered initially (if not empty),
    // we initialize them. But since we always start empty, this is optional.
    $('#personnelTable .designation_select').each(function() {
        if (!$(this).data('select2')) {
            $(this).select2({ placeholder: 'Search designation...', allowClear: true, width: '100%' });
        }
    });
    $('#vehicleTable .vehicle_select').each(function() {
        if (!$(this).data('select2')) {
            $(this).select2({ placeholder: 'Search vehicle category...', allowClear: true, width: '100%' });
        }
    });
    $('#equipmentTable .equipment_select').each(function() {
        if (!$(this).data('select2')) {
            $(this).select2({ placeholder: 'Search equipment category...', allowClear: true, width: '100%' });
        }
    });

    // ============================================================
    // 6. REPORT SELECTION
    // ============================================================

    $('#reportSelect').select2({
        placeholder: 'Search for a report...',
        allowClear: true
    });

    $('#reportSelect').on('change', function() {
        var selected = $(this).find(':selected');
        var val = selected.val();

        if (val) {
            var type = 'fire';
            var id = val;
            $('#reportType').val(type);
            $('#reportId').val(id);

            $.ajax({
                url: '{{ route("pumping-bills.get-report", ["type" => "__TYPE__", "id" => "__ID__"]) }}'
                    .replace('__TYPE__', type)
                    .replace('__ID__', id),
                type: 'GET',
                success: function(data) {
                    // Organisation
                    $('#organisationName').val(data.organisation_name);
                    $('#address').val(data.address);
                    $('#mobile').val(data.mobile);
                    $('#email').val(data.email);
                    $('#serviceDescription').val(data.service_description);

                    // Tables
                    populatePersonnel(data.personnel);
                    populateVehicles(data.vehicles);
                    populateEquipment(data.equipments);
                },
                error: function() {
                    alert('Could not fetch report details.');
                }
            });
        } else {
            // Clear all
            $('#reportType').val('');
            $('#reportId').val('');
            $('#organisationName').val('');
            $('#address').val('');
            $('#mobile').val('');
            $('#email').val('');
            $('#serviceDescription').val('');
            populatePersonnel([]);
            populateVehicles([]);
            populateEquipment([]);
        }
    });

    // ============================================================
    // 7. ADD / REMOVE ROWS
    // ============================================================

    // Personnel
    $('#addPersonnelRow').click(function() {
        var row = getPersonnelRow(null, 1, 1, 0, 0, 0);
        $('#personnelTable').append(row);
        initDesignationSelect(row);
        calculateTotals();
    });
    $(document).on('click', '.removePersonnelRow', function() {
        $(this).closest('tr').remove();
        calculateTotals();
    });

    // Vehicles
    $('#addVehicleRow').click(function() {
        var row = getVehicleRow(null, 0);
        $('#vehicleTable').append(row);
        triggerVehicleRow(row);
        calculateTotals();
    });
    $(document).on('click', '.removeVehicleRow', function() {
        $(this).closest('tr').remove();
        calculateTotals();
    });

    // Equipment
    $('#addEquipmentRow').click(function() {
        var row = getEquipmentRow(null, 0);
        $('#equipmentTable').append(row);
        triggerEquipmentRow(row);
        calculateTotals();
    });
    $(document).on('click', '.removeEquipmentRow', function() {
        $(this).closest('tr').remove();
        calculateTotals();
    });

    // ============================================================
    // 8. EVENT HANDLERS – PERSONNEL
    // ============================================================

    // Clamp minimum values for personnel
    $(document).on('blur', '.no_of_days, .no_of_person', function() {
        let val = parseInt($(this).val()) || 0;
        if (val < 1) {
            $(this).val(1);
            $(this).trigger('keyup');
        }
    });

    $(document).on('change', '.designation_select', function() {
        var row = $(this).closest('tr');
        var expense = $(this).find(':selected').data('expense') || 0;
        var da = $(this).find(':selected').data('da') || 0;
        row.find('.expense').val(expense);
        row.find('.da').val(da);
        row.find('.no_of_person').trigger('keyup');
    });

    $(document).on('keyup change', '.no_of_person, .no_of_days', function() {
        var row = $(this).closest('tr');
        var count = parseFloat(row.find('.no_of_person').val()) || 0;
        var days = parseFloat(row.find('.no_of_days').val()) || 1;
        var expense = parseFloat(row.find('.expense').val()) || 0;
        var da = parseFloat(row.find('.da').val()) || 0;

        var total = (expense * count * days) / 30;
        total += (total * da / 100);

        row.find('.person_total').val(total.toFixed(2));
        calculateTotals();
    });

    // ============================================================
    // 9. EVENT HANDLERS – VEHICLES & EQUIPMENT
    // ============================================================

    // Vehicle: selection
    $(document).on('change', '.vehicle_select', function() {
        var row = $(this).closest('tr');
        var mileage = $(this).find(':selected').data('mileage') || 0;
        var type = $(this).find(':selected').data('type') || '';
        row.find('.mileage_value').val(mileage);
        row.find('.mileage_type').val(type);
        row.find('.running_value').trigger('keyup');
    });

    // Vehicle: running (KM)
    $(document).on('keyup change', '.running_value', function() {
        var row = $(this).closest('tr');
        var running = parseFloat($(this).val()) || 0;
        var mileage = parseFloat(row.find('.mileage_value').val()) || 0;
        var fuelRate = parseFloat($('#fuelRate').val()) || 0;
        var mileageType = row.find('.mileage_type').val();

        var fuelUsed = 0;
        if (mileageType == 'per_km') {
            fuelUsed = mileage > 0 ? running / mileage : 0;
        } else {
            fuelUsed = running * mileage;
        }

        var total = fuelUsed * fuelRate;
        row.find('.vehicle_fuel_used').val(fuelUsed.toFixed(2));
        row.find('.vehicle_total').val(total.toFixed(2));
        calculateTotals();
    });

    // Equipment: selection
    $(document).on('change', '.equipment_select', function() {
        var row = $(this).closest('tr');
        var mileage = $(this).find(':selected').data('mileage') || 0;
        var type = $(this).find(':selected').data('type') || '';
        row.find('.equipment_mileage_value').val(mileage);
        row.find('.equipment_mileage_type').val(type);
        row.find('.equipment_running_value').trigger('keyup');
    });

    // Equipment: running (Hours)
    $(document).on('keyup change', '.equipment_running_value', function() {
        var row = $(this).closest('tr');
        var running = parseFloat($(this).val()) || 0;
        var mileage = parseFloat(row.find('.equipment_mileage_value').val()) || 0;
        var fuelRate = parseFloat($('#fuelRate').val()) || 0;
        var mileageType = row.find('.equipment_mileage_type').val();

        var fuelUsed = 0;
        if (mileageType == 'per_km') {
            fuelUsed = mileage > 0 ? running / mileage : 0;
        } else {
            fuelUsed = running * mileage;
        }

        var total = fuelUsed * fuelRate;
        row.find('.equipment_fuel_used').val(fuelUsed.toFixed(2));
        row.find('.equipment_total').val(total.toFixed(2));
        calculateTotals();
    });

    // Fuel rate change – recalculate all
    $('#fuelRate').on('change keyup', function() {
        $('.running_value').each(function() { $(this).trigger('keyup'); });
        $('.equipment_running_value').each(function() { $(this).trigger('keyup'); });
    });

    // ============================================================
    // 10. BILLING SUMMARY
    // ============================================================

    function calculateTotals() {
        let personnelTotal = 0;
        $('.person_total').each(function() { personnelTotal += parseFloat($(this).val()) || 0; });
        let vehicleTotal = 0;
        $('.vehicle_total').each(function() { vehicleTotal += parseFloat($(this).val()) || 0; });
        let equipmentTotal = 0;
        $('.equipment_total').each(function() { equipmentTotal += parseFloat($(this).val()) || 0; });
        let totalFuelExpense = vehicleTotal + equipmentTotal;
        let depreciation = totalFuelExpense * 0.25;
        $('#fuelExpense').val(totalFuelExpense.toFixed(2));
        $('#depreciationExpense').val(depreciation.toFixed(2));
        $('#personnelExpense').val(personnelTotal.toFixed(2));
        let subtotal = totalFuelExpense + depreciation + personnelTotal;
        let cgst = subtotal * 0.09;
        let sgst = subtotal * 0.09;
        let grand = subtotal + cgst + sgst;
        $('#cgstAmount').val(cgst.toFixed(2));
        $('#sgstAmount').val(sgst.toFixed(2));
        $('#grandTotal').val(grand.toFixed(2));
    }

    // ============================================================
    // 11. INITIALISE WITH EMPTY ROWS
    // ============================================================

    populatePersonnel([]);
    populateVehicles([]);
    populateEquipment([]);
});
</script>
@endsection